#!/usr/bin/env ruby
#^syntax detection

site "http://community.opscode.com/api/v1"

cookbook "apt"
cookbook "build-essential"
cookbook "user",
  :git => "git://github.com/fnichol/chef-user.git"
cookbook "git"
cookbook "memcached"
cookbook "mysql"
cookbook "nginx"
cookbook "ntp"
cookbook "python"
cookbook "sudo"
cookbook "vim"
